# Generated by Django 3.0 on 2019-12-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='resume_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
